version: '3'
services:
  your_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pacman
    restart: on-failure
    ports:
      - "0.0.0.0:80:80"
    volumes:
        - .:/var/www/html
    networks:
      internal_network:
        ipv4_address: 192.168.1.100

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
